export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const RE_REGISTER_SUCCESS = "RE_REGISTER_SUCCESS";
export const RE_REGISTER_FAIL = "RE_REGISTER_FAIL";

export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";  
export const VERIFY_OTP_FAIL = "VERIFY_OTP_FAIL";       
export const OTP_EXPIRED = "OTP_EXPIRED";                

export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";   