export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_ROLE = "SET_ROLE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const RE_REGISTER_SUCCESS = "RE_REGISTER_SUCCESS";
export const RE_REGISTER_FAIL = "RE_REGISTER_FAIL";